### ISSUE TITLE
demo is 502 Bad Gateway

### ISSUE THREAD

**Issue by ginolhac** [gadenbuie/regexplain#24]
Hello Garrick,

just to let you know that this link:
https://apps.garrickadenbuie.com/regexplain
is error 502. 

Thanks again for all the development you do, appreciate all your pkgs.

**Comment by gadenbuie** [comment]
Fixed, thanks for the heads up!

**Comment by ginolhac** [comment]
Thanks to you! and also for taking a tour to my repo ;)

**Comment by gadenbuie** [comment]
Np! I'm excited to check out [upnews](https://github.com/ginolhac/upnews)!

**Comment by ginolhac** [comment]
ah ah ;) it is outdated but was a lot of fun to do it. I wanted NO tidyverse as an exercise. 
And it justified what tidyverse people are teaching/saying: "let students eat the cake first".
I learnt a lot doing this and without pressure since I had a backup solution in case of emergency.
