### ISSUE TITLE
empty textblock not correctly handled in RegEx panel

### ISSUE THREAD

**Issue by HanOostdijk** [gadenbuie/regexplain#9]
Experimenting with the toolbox I tried to change text between parentheses. A pair of parentheses without any text in between is not handled correctly in the *RegEx panel*. However the *Output panel* shows the expected output.  See end of this post.

As a possible related issue I have not succeeded in copying a regex with the *send RegEx to Console* button. The *regexplain* applet (?) just ends without visible indication that a copy is done (to console, editor or clipboard). 
This happens even when I try to change '2017' in '2018' with gsub with the applet: in this case the  *RegEx* and *Output panel* both show the expected display but the  *send RegEx to Console* button only ends the applet.

I am using RStudio Version 1.2.502 and R packages as listed below in *sessionInfo*.

Thanks for bringing this software to the public domain.

 *RegEx panel*:
![regex_panel](https://user-images.githubusercontent.com/13506389/38778783-f0a2fb50-40be-11e8-8115-5fce9d70c443.png)

 *Output panel*:
![output_panel](https://user-images.githubusercontent.com/13506389/38778788-fee26944-40be-11e8-9222-bd0c3a07bc10.png)

> sessionInfo()
> R version 3.4.1 (2017-06-30)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252 
> [2] LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods  
> [7] base     
> 
> other attached packages:
> [1] shiny_1.0.5    bindrcpp_0.2.2
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.16     rstudioapi_0.7   bindr_0.1.1     
>  [4] magrittr_1.5     tidyselect_0.2.4 xtable_1.8-2    
>  [7] R6_2.2.2         rlang_0.2.0      dplyr_0.7.4     
> [10] tools_3.4.1      miniUI_0.1.1     htmltools_0.3.6 
> [13] yaml_2.1.18      assertthat_0.2.0 digest_0.6.15   
> [16] tibble_1.4.2     regexplain_0.2.1 tidyr_0.8.0     
> [19] purrr_0.2.4      curl_3.1         glue_1.2.0      
> [22] mime_0.5         compiler_3.4.1   pillar_1.2.1    
> [25] jsonlite_1.5     httpuv_1.3.6.2   pkgconfig_2.0.1 
>

**Comment by HanOostdijk** [comment]
I have tried your `fix-issue-9` fix and this gives the display you mentioned above.
So I would say: issue resolved.

However this only works if I have used the ` library(bindrcpp)`  statement in the session before.
This is not specific for your `fix-issue-9` fix because it also occurred in the standard version.
If  *bindrcpp* is not present it is apparently loaded by the applet. The attached screenprint shows a warning (NB I understand why I get the warning) in the RegEx panel and none of the selected groups are indicated  (but the Output panel is okay: i.e as in the screenprint in the first message).

*RegEx panel with message:*
![without_bindrcpp](https://user-images.githubusercontent.com/13506389/38783832-47a4f2d4-4108-11e8-9a86-1590345051f3.png)

Regarding the other issue: you probably meant to say *I can **not** replicate the issue with RStudio 1.0 or 1.1 (on Mac/Unix).*? Meaning you have no errors there?

**Comment by HanOostdijk** [comment]
My remarks in earlier comments where all related to RStudio Version 1.2.502
Just now I installed version 1.1.442 (apparently the latest regular version) and tried your `fix-issue-9` fix.

The *Send RegEx to Console* button works here indeed and the issue with groups that start and end at the same point is indeed resolved. But also with 1.1.442 the execution of the `library(bindrcpp)` statement before using ` regexplain` is necessary to see the groups in the RegEx panel.

**Comment by gadenbuie** [comment]
Glad to hear the fix and the buttons are working in RStudio 1.1. I've opened #10 to track future issues with RStudio and version 1.2.

I can't reproduce the issue with `bindrcpp`. That package is imported by `dplyr` and I'm thinking that maybe having installed the binary version of `bindrcpp` on Windows with R 3.4.1 when the binary was built against R 3.4.4 might be the culprit. I don't have easy access to a Windows machine available, so I can't reproduce. But I'm going to remove the dependency on `dplyr` (#11), which shouldn't be hard to do and will resolve this issue.
